name: Bot Run

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'  # At minute 30 (once an hour)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_JSONSTORAGE_KEY: ${{ secrets.JSONSTORAGE_KEY }}
        envkey_JSONSTORAGE_OBJECT: ${{ secrets.JSONSTORAGE_OBJECT }}
        envkey_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        envkey_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        envkey_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        envkey_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        envkey_TWITTER_USER: ${{ secrets.TWITTER_USER }}
        file_name: .env

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Pull the bot image
      run: docker pull docker.pkg.github.com/addshore/twitter-wikidatameter/bot:latest

    - name: Run the bot image
      run: docker run --rm --env-file .env docker.pkg.github.com/addshore/twitter-wikidatameter/bot:latest
